"""Conservative clinical PERSON-NER exceptions, not a complete medical ontology.

Only exact span matches qualify. Identifiers and explicitly labelled names retain
precedence. Deployments can add reviewed terms without modifying application code.
"""

DEFAULT_CLINICAL_TERMS = (
    "metformin",
    "atorvastatin",
    "rosuvastatin",
    "simvastatin",
    "pravastatin",
    "insulin",
    "glipizide",
    "gliclazide",
    "glimepiride",
    "sitagliptin",
    "empagliflozin",
    "dapagliflozin",
    "semaglutide",
    "liraglutide",
    "pioglitazone",
    "amlodipine",
    "lisinopril",
    "enalapril",
    "ramipril",
    "losartan",
    "valsartan",
    "telmisartan",
    "metoprolol",
    "bisoprolol",
    "carvedilol",
    "atenolol",
    "hydrochlorothiazide",
    "furosemide",
    "spironolactone",
    "aspirin",
    "clopidogrel",
    "warfarin",
    "apixaban",
    "rivaroxaban",
    "heparin",
    "enoxaparin",
    "levothyroxine",
    "methimazole",
    "amoxicillin",
    "azithromycin",
    "doxycycline",
    "ceftriaxone",
    "cephalexin",
    "ciprofloxacin",
    "metronidazole",
    "penicillin",
    "paracetamol",
    "acetaminophen",
    "ibuprofen",
    "naproxen",
    "diclofenac",
    "omeprazole",
    "pantoprazole",
    "famotidine",
    "ondansetron",
    "prednisone",
    "prednisolone",
    "dexamethasone",
    "budesonide",
    "salbutamol",
    "albuterol",
    "montelukast",
    "cetirizine",
    "loratadine",
    "gabapentin",
    "pregabalin",
    "sertraline",
    "fluoxetine",
    "escitalopram",
    "duloxetine",
    "allopurinol",
    "colchicine",
    "ferrous sulfate",
    "folic acid",
    "cyanocobalamin",
    "hba1c",
    "hemoglobin a1c",
    "glycated hemoglobin",
    "glucose",
    "fasting glucose",
    "creatinine",
    "urea",
    "bun",
    "egfr",
    "sodium",
    "potassium",
    "chloride",
    "bicarbonate",
    "calcium",
    "magnesium",
    "phosphate",
    "albumin",
    "bilirubin",
    "hemoglobin",
    "haemoglobin",
    "hematocrit",
    "haematocrit",
    "platelets",
    "leukocytes",
    "neutrophils",
    "lymphocytes",
    "eosinophils",
    "ferritin",
    "transferrin",
    "cholesterol",
    "triglycerides",
    "hdl",
    "ldl",
    "tsh",
    "thyroxine",
    "troponin",
    "crp",
    "c-reactive protein",
    "esr",
    "inr",
    "prothrombin time",
    "aptt",
    "alt",
    "ast",
    "alkaline phosphatase",
    "vitamin b12",
    "vitamin d",
    "blood pressure",
    "heart rate",
    "oxygen saturation",
    "diabetes mellitus",
    "type 2 diabetes",
    "hypertension",
    "hypothyroidism",
    "hyperthyroidism",
    "hyperlipidemia",
    "dyslipidemia",
    "asthma",
    "copd",
    "pneumonia",
    "bronchitis",
    "anemia",
    "anaemia",
    "heart failure",
    "atrial fibrillation",
    "coronary artery disease",
    "myocardial infarction",
    "chronic kidney disease",
    "acute kidney injury",
    "osteoarthritis",
    "rheumatoid arthritis",
    "osteoporosis",
    "gastroesophageal reflux disease",
    "urinalysis",
    "electrocardiogram",
    "echocardiogram",
    "ultrasound",
    "radiography",
    "computed tomography",
    "magnetic resonance imaging",
)
